//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLogin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    public partial class User
    {
        public int UserID { get; set; }
        [Required(ErrorMessage = "Podaj login", AllowEmptyStrings = false)]
        [DisplayName("Login")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Podaj haslo", AllowEmptyStrings = false)]
        [DataType(DataType.Password)]
        [DisplayName("Haslo")]
        public string Password { get; set; }
    }
}
