//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLogin.Resources {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeTexts() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVCLogin.Resources.HomeTexts", typeof(HomeTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu AKTUALNIE WYŚWIETLANA STRONA.
        /// </summary>
        public static string LETSCSSTEXT
        {
            get
            {
                return ResourceManager.GetString("LETSCSSTEXT", resourceCulture);
            }
        }
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu AKTUALNIE WYŚWIETLANA STRONA.
        /// </summary>
        public static string FOUNDATION
        {
            get
            {
                return ResourceManager.GetString("FOUNDATION", resourceCulture);
            }
        }
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu AKTUALNIE WYŚWIETLANA STRONA.
        /// </summary>
        public static string COOKIE
        {
            get
            {
                return ResourceManager.GetString("COOKIE", resourceCulture);
            }
        }
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu AKTUALNIE WYŚWIETLANA STRONA.
        /// </summary>
        public static string BROKER
        {
            get
            {
                return ResourceManager.GetString("BROKER", resourceCulture);
            }
        }
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu AKTUALNIE WYŚWIETLANA STRONA.
        /// </summary>
        public static string GOTIT
        {
            get
            {
                return ResourceManager.GetString("GOTIT", resourceCulture);
            }
        }
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu AKTUALNIE WYŚWIETLANA STRONA.
        /// </summary>
        public static string AGENCY
        {
            get
            {
                return ResourceManager.GetString("AGENCY", resourceCulture);
            }
        }
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu AKTUALNIE WYŚWIETLANA STRONA.
        /// </summary>
        public static string SILESIAN
        {
            get
            {
                return ResourceManager.GetString("SILESIAN", resourceCulture);
            }
        }


        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu AKTUALNIE WYŚWIETLANA STRONA.
        /// </summary>
        public static string ACTUALYDISPLAYSITE {
            get {
                return ResourceManager.GetString("ACTUALYDISPLAYSITE", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Adres: .
        /// </summary>
        public static string ADRESS {
            get {
                return ResourceManager.GetString("ADRESS", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Mój pierwszy program napisany w C# przy użyciu frameworka .NET WPF.
        ///                            Jest to program do tworzenia oferty ubezpieczeniowej w postaci gotowego maila.
        ///                            Pomysł pojawił mi się jeszcze w chwili kiedy pracowałem w ubezpieczeniach.
        ///                            Realizację pomysłu zacząłem w chwili, gdy nauczyłem się C#.
        ///                            Czas napisania programu to ok 2 tygodni, gdzie wcześniej nigdy nie miałem
        ///                            styczności  [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string APPTEXT {
            get {
                return ResourceManager.GetString("APPTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Idąc dalej w las postanowiłem zapoznać się trochę z technologią ASP.NET MVC.
        ///                            Moją motywacją było uzupełnienie technologii .NET o kolejny framework i chęć poznania czegoś, o czym tak wiele się mówi i pisze w internecie.
        ///                            Swoją przygodę zacząłem od stworzenia okna logowania, aż po widoki poszczególnych stron.
        ///                            Z uwagi na fakt, iż z HTML, CSS oraz Bootstrapem miałem już wiele razy do czynienia i wiem co nie co na ten temat,
        ///  [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string ASPTEXT {
            get {
                return ResourceManager.GetString("ASPTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu PODSTAWY.
        /// </summary>
        public static string BASICS {
            get {
                return ResourceManager.GetString("BASICS", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Data ur..
        /// </summary>
        public static string BIRTHDATE {
            get {
                return ResourceManager.GetString("BIRTHDATE", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Powiedzieć, że znam bootstrapa od deski do deski to trochę zbyt wiele, natomiast radzę sobie z nim,
        ///                            wiem z czym należy go jeść, aby był jak najlepszy, znam zasady odpowiedzialne za responsywność stron,
        ///                            rozmieszczenie, a także inne podstawowe funkcje tego Frameworka.
        ///                            Jak z powyższymi po prostu brakuje mi doświadczenia, ze względu na to iż bootstrapa używałem tylko w dwóch projektach.
        ///                            Nie mogę j [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string BOOTTEXT {
            get {
                return ResourceManager.GetString("BOOTTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pracodawca.
        /// </summary>
        public static string COMPANY {
            get {
                return ResourceManager.GetString("COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu #KONTAKT.
        /// </summary>
        public static string CONTACT {
            get {
                return ResourceManager.GetString("CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu jeżeli udało mi się Państwa zainteresować swoją osobą i są Państwo chętni do podjęcia współpracy
        ///                                      ze mną to proszę o kontakt telefoniczny lub mailowy.
        ///                                      Dla Państwa wygody udostępniam także skype, viber oraz what&apos;s up..
        /// </summary>
        public static string CONTACTTEXT {
            get {
                return ResourceManager.GetString("CONTACTTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu C# uczę się od lutego 2018r, do tej pory opanowałem solidne podstawy.
        ///                            W tym czasie wykonywałem zadania z.
        /// </summary>
        public static string CSHARP1 {
            get {
                return ResourceManager.GetString("CSHARP1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu , rozwiązywałem zadania z książek i uczelni wyższych.
        ///Ponadto miałem dostęp i korzystałem z takich gier jak.
        /// </summary>
        public static string CSHARP2 {
            get {
                return ResourceManager.GetString("CSHARP2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Powyższe pomoce naukowe pozwoliły mi opanować C# w stopniu, który umożliwił mi na dalszy rozwój, napisanie aplikacji WPF oraz stworzenie prostej strony opartej o ASP.NET MVC.
        /// </summary>
        public static string CSHARP3 {
            get {
                return ResourceManager.GetString("CSHARP3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu CSS zawsze był nieodzwoną częścią przy tworzeniu stron WWW, natomiast kiedy pierwszy raz się z nim zetknąłem to był
        ///                            dla mnie niczym magiczna księga napisana w obcym języku.
        ///                            Na moje szczęście jak to z każdą rzeczą, z którą zazwyczaj się stykam, został on przeze mnie opanowany w stopniu
        ///                            mniejszym, bądź większym.
        ///                            Niestety z uwagi na fakt, iż nie piszę stron na codzień, to też moja znajomość CSS3  [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string CSSTEXT {
            get {
                return ResourceManager.GetString("CSSTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu DANE.
        /// </summary>
        public static string DATA {
            get {
                return ResourceManager.GetString("DATA", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Inżynierii Materiałowej i Metalurgii.
        /// </summary>
        public static string DEPARTMENT {
            get {
                return ResourceManager.GetString("DEPARTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wydział: .
        /// </summary>
        public static string DEPARTMENTNAME {
            get {
                return ResourceManager.GetString("DEPARTMENTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu OPIS: .
        /// </summary>
        public static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu #POBIERZ.
        /// </summary>
        public static string DOWNLOAD {
            get {
                return ResourceManager.GetString("DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu WYKSZTAŁCENIE.
        /// </summary>
        public static string EDUCATION {
            get {
                return ResourceManager.GetString("EDUCATION", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wpisz login.
        /// </summary>
        public static string EMPTYFIELD1 {
            get {
                return ResourceManager.GetString("EMPTYFIELD1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wpisz hasło.
        /// </summary>
        public static string EMPTYFIELD2 {
            get {
                return ResourceManager.GetString("EMPTYFIELD2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Prosta strona napisana na prośbę znajomego,
        ///                            który posiadał firmę developerską.
        ///                            Layaut, grafika oraz kod mojego autorstwa. Zewnętrznie jako gotowy
        ///                            komponent został wykorzystany fragment dotyczący wyświetlania galerii..
        /// </summary>
        public static string EUROMAXTEXT {
            get {
                return ResourceManager.GetString("EUROMAXTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu DOŚWIADCZENIE.
        /// </summary>
        public static string EXPERIENCE {
            get {
                return ResourceManager.GetString("EXPERIENCE", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kierunek: .
        /// </summary>
        public static string FIELDOFSTUDY {
            get {
                return ResourceManager.GetString("FIELDOFSTUDY", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zarządzanie i Inżynieria Produkcji.
        /// </summary>
        public static string FIELDSTUDYNAME {
            get {
                return ResourceManager.GetString("FIELDSTUDYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu GITHUB.
        /// </summary>
        public static string GITHUB {
            get {
                return ResourceManager.GetString("GITHUB", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu GIT, system kontroli wersji. Niejedna książka została o nim napisana, z tego co zdążyłem zauważyć.
        ///                            Niestety ja nie mam za wiele do napisania. Wiem, że istnieje, korzystałem, mam konto na GIT HUB,
        ///                            jednak brak mi konkretnego doświadczenia w obsłudze GITa, zwłaszcza przy pracy w zespole, co jest spowodowane
        ///                            tym, iż uczę się wszystkiego sam.
        ///                            Reasumując podstawy znam, jednak nawet po przeczytaniu m [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string GITTEXT {
            get {
                return ResourceManager.GetString("GITTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zespół Szkół Zawodowych nr 2 w Bytomiu.
        /// </summary>
        public static string HIGHSCHOOLNAME {
            get {
                return ResourceManager.GetString("HIGHSCHOOLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Technik Mechanik.
        /// </summary>
        public static string HIGHSCHOOLSPEC {
            get {
                return ResourceManager.GetString("HIGHSCHOOLSPEC", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ZAINTERESOWANIA.
        /// </summary>
        public static string HOBBY {
            get {
                return ResourceManager.GetString("HOBBY", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Astronomia, programy naukowe, programowanie, gry (rpg, fpp, rts, planszowe, mmorpg)..
        /// </summary>
        public static string HOBBYTEXT {
            get {
                return ResourceManager.GetString("HOBBYTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Z HTML mam do czynienia odkąd pamiętam. Moja przygoda z tym językiem rozpoczęła się jeszcze w latach &apos;90,
        ///                            kiedy jako uczeń szkoły podstawowej dostałem pierwszy komputer, a następnie rozpocząłem lekcje informatyki
        ///                            w szkole. Od tamtej pory stworzyłem sporo stron www, niestety przetrwały do dziś tylko dwie, które prezentuję
        ///                            powyżej. Swoją pierwszą poważną stronę zrobiłem w &apos;98 roku, na olimpiadę informatyczną i zająłem trzec [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string HTMLTEXT {
            get {
                return ResourceManager.GetString("HTMLTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ŚREDNIO ZAAWANSOWANY.
        /// </summary>
        public static string INTERMEDIATE {
            get {
                return ResourceManager.GetString("INTERMEDIATE", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu j. angielski B2.
        /// </summary>
        public static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu JĘZYKI OBCE.
        /// </summary>
        public static string LANGUAGES {
            get {
                return ResourceManager.GetString("LANGUAGES", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu LOGIN.
        /// </summary>
        public static string LOGIN {
            get {
                return ResourceManager.GetString("LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ZALOGUJ.
        /// </summary>
        public static string LOGINBUTTON {
            get {
                return ResourceManager.GetString("LOGINBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu LOGOWANIE.
        /// </summary>
        public static string LOGINLABLE {
            get {
                return ResourceManager.GetString("LOGINLABLE", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Strona powstała w oparciu o technologię ASP.NET MVC, framework Bootstrap oraz CSS3. Tym samym chciałem zaprezentować swoje umiejętności, dlatego też w dalszej części znajdują się wszelakie projekty przeze mnie zrealizowane oraz parę informacji dotyczących mojej osoby..
        /// </summary>
        public static string LOGINPAGETEXTMAIN {
            get {
                return ResourceManager.GetString("LOGINPAGETEXTMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Szanowni Państwo,.
        /// </summary>
        public static string LOGINPAGETEXTMRMRS {
            get {
                return ResourceManager.GetString("LOGINPAGETEXTMRMRS", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Login i Hasło do strony zostały podane w CV, którego strona jest uzupełnieniem..
        /// </summary>
        public static string LOGINPAGETEXTSECONDARY {
            get {
                return ResourceManager.GetString("LOGINPAGETEXTSECONDARY", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu WYLOGUJ.
        /// </summary>
        public static string LOGOUT {
            get {
                return ResourceManager.GetString("LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Utrzymywanie kontaktu z powierzonym klientem,.
        /// </summary>
        public static string MAURFIELD1 {
            get {
                return ResourceManager.GetString("MAURFIELD1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zawieranie umów ubezpieczeniowych,.
        /// </summary>
        public static string MAURFIELD2 {
            get {
                return ResourceManager.GetString("MAURFIELD2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Prowadzenie dokumentacji związanej z procedurami
        ///                            zawierania umów ubezpieczeniowych.
        /// </summary>
        public static string MAURFIELD3 {
            get {
                return ResourceManager.GetString("MAURFIELD3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pozyskiwanie nowych klientów.
        /// </summary>
        public static string MAURFIELD4 {
            get {
                return ResourceManager.GetString("MAURFIELD4", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Prowadzenie dokumentacji rozliczeniowej agencji.
        /// </summary>
        public static string MAURFIELD5 {
            get {
                return ResourceManager.GetString("MAURFIELD5", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu #O MNIE.
        /// </summary>
        public static string ME {
            get {
                return ResourceManager.GetString("ME", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu WIĘCEJ.
        /// </summary>
        public static string MOREBUTTON {
            get {
                return ResourceManager.GetString("MOREBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu BRAK.
        /// </summary>
        public static string NONE {
            get {
                return ResourceManager.GetString("NONE", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu KONFIGURATOR OFERT.
        /// </summary>
        public static string OFFERCONFIGURATOR {
            get {
                return ResourceManager.GetString("OFFERCONFIGURATOR", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu INNE PROJEKTY.
        /// </summary>
        public static string OTHERPROJECTS {
            get {
                return ResourceManager.GetString("OTHERPROJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu HASŁO.
        /// </summary>
        public static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Telefon: .
        /// </summary>
        public static string PHONE {
            get {
                return ResourceManager.GetString("PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu PROGRAMOWANIE.
        /// </summary>
        public static string PROGRAMMING {
            get {
                return ResourceManager.GetString("PROGRAMMING", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu C#. WPF, ASP.NET MVC,.
        /// </summary>
        public static string PROGRAMMINGFIELD1 {
            get {
                return ResourceManager.GetString("PROGRAMMINGFIELD1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu HTML. CSS3, BOOTSTRAP,.
        /// </summary>
        public static string PROGRAMMINGFIELD2 {
            get {
                return ResourceManager.GetString("PROGRAMMINGFIELD2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu VISUAL STUDIO 2017,.
        /// </summary>
        public static string PROGRAMMINGFIELD3 {
            get {
                return ResourceManager.GetString("PROGRAMMINGFIELD3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu GIT, SQL, IIS,.
        /// </summary>
        public static string PROGRAMMINGFIELD4 {
            get {
                return ResourceManager.GetString("PROGRAMMINGFIELD4", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu SCRUM, AGILE.
        /// </summary>
        public static string PROGRAMMINGFIELD5 {
            get {
                return ResourceManager.GetString("PROGRAMMINGFIELD5", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu PROJEKTY: .
        /// </summary>
        public static string PROJ {
            get {
                return ResourceManager.GetString("PROJ", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu #PROJEKTY.
        /// </summary>
        public static string PROJECTS {
            get {
                return ResourceManager.GetString("PROJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Chęć rozwoju zawodowego.
        /// </summary>
        public static string SKILLFIELD6 {
            get {
                return ResourceManager.GetString("SKILLFIELD6", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ATUTY.
        /// </summary>
        public static string SKILLS {
            get {
                return ResourceManager.GetString("SKILLS", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Analityczne myślenie.
        /// </summary>
        public static string SKILLSFIELD1 {
            get {
                return ResourceManager.GetString("SKILLSFIELD1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Praca zespołowa.
        /// </summary>
        public static string SKILLSFIELD2 {
            get {
                return ResourceManager.GetString("SKILLSFIELD2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Komunikatywność.
        /// </summary>
        public static string SKILLSFIELD3 {
            get {
                return ResourceManager.GetString("SKILLSFIELD3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Szybkie przyswajanie wiedzy.
        /// </summary>
        public static string SKILLSFIELD4 {
            get {
                return ResourceManager.GetString("SKILLSFIELD4", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Odporność na stres.
        /// </summary>
        public static string SKILLSFIELD5 {
            get {
                return ResourceManager.GetString("SKILLSFIELD5", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Chęć rozwoju zawodowego.
        /// </summary>
        public static string SKILLSFIELD6 {
            get {
                return ResourceManager.GetString("SKILLSFIELD6", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Technolog programista obrabiarek sterowanych numerycznie..
        /// </summary>
        public static string SPECIALIZATIONNAME {
            get {
                return ResourceManager.GetString("SPECIALIZATIONNAME", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Specjalizacja: .
        /// </summary>
        public static string SPECJALIZATION {
            get {
                return ResourceManager.GetString("SPECJALIZATION", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Naprawa, konserwacja elementów bierzących,.
        /// </summary>
        public static string SPORTFIELD1 {
            get {
                return ResourceManager.GetString("SPORTFIELD1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Obsługa, konfiguracja szafy serwerowej,.
        /// </summary>
        public static string SPORTFIELD2 {
            get {
                return ResourceManager.GetString("SPORTFIELD2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Rozwiązywanie pojawiających się problemów związanych z obsługą hostelu,.
        /// </summary>
        public static string SPORTFIELD3 {
            get {
                return ResourceManager.GetString("SPORTFIELD3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Obsługa gości, w szczególności zagranicznych..
        /// </summary>
        public static string SPORTFIELD4 {
            get {
                return ResourceManager.GetString("SPORTFIELD4", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu SQL - do niedawna trzy litery które nie mówiły mi nic poza tym, iż są to bazy danych.
        ///                            Jednak i na to przyszedł czas, najpierw szybki kurs na youtube na kanale           .
        /// </summary>
        public static string SQLTEXT {
            get {
                return ResourceManager.GetString("SQLTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu , gdzie w bardzo przystępny i prosty sposób wytłumaczone są podstawy.
        ///                            Następnie instalacja XAMPP i trochę treningu na localhoscie, co pozwoliło na opanowanie
        ///                            podstawowych zapytań select, from, delete, update, truncate oraz zabawę na myphpadmin.
        ///                            Następnie przyszedł czas na stworzenie bazy do logowania w projekcje mvc, ponieważ nie chciałem
        ///                            aby ludzie z zewnątrz mieli dostęp do tej strony.
        ///     [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string SQLTEXT1 {
            get {
                return ResourceManager.GetString("SQLTEXT1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Placówka: .
        /// </summary>
        public static string STUDYPLACE {
            get {
                return ResourceManager.GetString("STUDYPLACE", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Opracowanie wyników prób zmęczenia cieplno-mechanicznego na podstawie stali: X20CrMoV12.1, P91 i P92..
        /// </summary>
        public static string STUDYTOPIC {
            get {
                return ResourceManager.GetString("STUDYTOPIC", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Utrzymywanie relacji z klientami strategicznymi,.
        /// </summary>
        public static string SZLIPSFIELD1 {
            get {
                return ResourceManager.GetString("SZLIPSFIELD1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Przygotowywanie dokumentacji SIWZ,.
        /// </summary>
        public static string SZLIPSFIELD2 {
            get {
                return ResourceManager.GetString("SZLIPSFIELD2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nadzór nad pozostałymi członkami zespołu (2 ludzi).
        /// </summary>
        public static string SZLIPSFIELD3 {
            get {
                return ResourceManager.GetString("SZLIPSFIELD3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Przygotowywanie dokumentacji dla księgowości,.
        /// </summary>
        public static string SZLIPSFIELD4 {
            get {
                return ResourceManager.GetString("SZLIPSFIELD4", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tworzenie umów flotowych dla tzw. dużych flot,.
        /// </summary>
        public static string SZLIPSFIELD5 {
            get {
                return ResourceManager.GetString("SZLIPSFIELD5", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Negocjacje warunków umów z towarzystwami ubezpieczeniowymi,.
        /// </summary>
        public static string SZLIPSFIELD6 {
            get {
                return ResourceManager.GetString("SZLIPSFIELD6", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Prowadzenie rozliczeo wewnętrznych jak i zewnętrznych,
        ///                            wystawianie faktur, obsługa dokumentacji biurowej.
        /// </summary>
        public static string SZLIPSFIELD7 {
            get {
                return ResourceManager.GetString("SZLIPSFIELD7", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Strona dla firmy w której pracowałem, pisana całkowicie hobbystycznie w celu
        ///                            nauczenia się frameworka Bootstrap. Layaut, projekt graficzny oraz pomysł
        ///                            w całości mojego autorstwa. Niektóre rozwiązania wprowadzone w oparciu
        ///                            o StackOwerflow oraz Gotowe szablony JQuery, przerobione na własny użytek w miarę potrzeb..
        /// </summary>
        public static string SZLIPSTEXT {
            get {
                return ResourceManager.GetString("SZLIPSTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu #TECHNOLOGIE.
        /// </summary>
        public static string TECHNOLOGIES {
            get {
                return ResourceManager.GetString("TECHNOLOGIES", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Temat pracy dyplomowej: .
        /// </summary>
        public static string THESISTOPIC {
            get {
                return ResourceManager.GetString("THESISTOPIC", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Visual studio 2017, program do pisania programów, wielka rzecz, tak myślałem gdy instalował się na moim SSD.
        ///                            Dlaczego akurat Visual studio? Kolega który jest programistą polecił mi go, drugim powodem było to, że jest
        ///                            to kompilator stworzony przez Microsoft, tak samo jak cały .NET.
        ///                            Pierwsze kroki nie były łatwe, ale jak już wspominałem - wyznaję zasadę, iż wszystkiego można się nauczyć
        ///                            w większ [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string VISUALTEXT {
            get {
                return ResourceManager.GetString("VISUALTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Okres.
        /// </summary>
        public static string WORKTIME {
            get {
                return ResourceManager.GetString("WORKTIME", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu W trzecim miesiącu nauki programowania nadszedł czas na pierwszą samodzielnie napisaną aplikację okienkową. Wybór padł początkowo na technologię WPF pomimo, iż nie za bardzo wiedziałem z czym to się je. Pierwsze próby napisania czego-kolwiek były ciężkie ponieważ nie wiedziałem co, gdzie i jak powinno zostać zrobione. Po tygodniu miałem już gotowy program, a następnie wprowadziłem kilka poprawek i ulepszeń..
        /// </summary>
        public static string WPFTEXT {
            get {
                return ResourceManager.GetString("WPFTEXT", resourceCulture);
            }
        }
    }
}
