//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SettlementMenager_v_1._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class connectionSetup
    {
        public string checkedCheckbox { get; set; }
        public string ipAdress { get; set; }
        public string connectionPort { get; set; }
        public string passwordToDatabase { get; set; }
        public string loginToDatabase { get; set; }
        public int id { get; set; }
    }
}
