//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SettlementMenager_v_1._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class userPolicyData
    {
        public int Id { get; set; }
        public string userName { get; set; }
        public string policyNumber { get; set; }
        public string brokerName { get; set; }
        public Nullable<System.DateTime> fullDate { get; set; }
        public string policyStatus { get; set; }
    }
}
