//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SettlementMenager_v_1._1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"connectionString=""metadata=res://*/DataModelDB.csdl|res://*/DataModelDB.ssdl|res://*/DataModelDB.msl;provider=System.Data.SqlClient;
         provider connection string=&quot;&#xD;&#xA; data source=localhost\SQLEXPRESS;Database=Database.mdf;integrated security=True;connect timeout=30;
         MultipleActiveResultSets=True;App=EntityFramework&quot;"" providerName=""System.Data.EntityClientproviderName=""System.Data.EntityClient""
")]
        public string entityLocalDb {
            get {
                return ((string)(this["entityLocalDb"]));
            }
            set {
                this["entityLocalDb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"connectionString=""metadata=res://*/DataModelDB.csdl|res://*/DataModelDB.ssdl|res://*/DataModelDB.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=25.51.93.64;initial catalog=Database.mdf;persist security info=True;user id=sa;password=palka8;MultipleActiveResultSets=True;App=EntityFramework&quot;"" providerName=""System.Data.EntityClient""")]
        public string entityLanDb {
            get {
                return ((string)(this["entityLanDb"]));
            }
            set {
                this["entityLanDb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"Data Source=localhost\\\\SQLEXPRESS; Database = master; Integrated security=SSPI;\"" +
            "")]
        public string masterLocalDb {
            get {
                return ((string)(this["masterLocalDb"]));
            }
            set {
                this["masterLocalDb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=25.51.93.64;Network Library=DBMSSOCN; Initial Catalog = Databases; Da" +
            "tabase=Database.mdf; User ID = sa; Password = palka8")]
        public string masterLanDb {
            get {
                return ((string)(this["masterLanDb"]));
            }
            set {
                this["masterLanDb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\\SQLEXPRESS; Database = Database.mdf; Integrated security=SS" +
            "PI")]
        public string databaseLocalDb {
            get {
                return ((string)(this["databaseLocalDb"]));
            }
            set {
                this["databaseLocalDb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=25.51.93.64;Network Library=DBMSSOCN; Initial Catalog = Databases; Da" +
            "tabase=master; User ID = sa; Password = palka8")]
        public string databaseLanDb {
            get {
                return ((string)(this["databaseLanDb"]));
            }
            set {
                this["databaseLanDb"] = value;
            }
        }
    }
}
